### PR TITLE
docs: license is Apache, not BSD

### PR DESCRIPTION
**Pull request by elharo**
@silvolu @chingor13

### CODE REVIEW

**Review by chingor13 — CHANGES_REQUESTED** [review]
The license on this repo is/has been BSD 3-clause since its inception.

**Comment by elharo** [comment]
The LICENSE file at https://github.com/googleapis/google-auth-library-java/blob/master/LICENSE says otherwise. One of these needs to be updated to be match the other.

**Comment by elharo** [comment]
The LICENSE file at https://github.com/googleapis/google-auth-library-java/blob/master/LICENSE says otherwise. One of these needs to be updated to be match the other.

**Comment by elharo** [comment]
Looks like synthtool changed this:

https://github.com/googleapis/google-auth-library-java/pull/519/files

**Pull request closed without merging**
