### PR TITLE
Add support for Google Extensible Service Proxy

### PR DESCRIPTION
**Pull request by maguro**
Cloud Endpoints' Extensible Service Proxy only takes JWTs, not access tokens.  This
change provides the ability to trasform UserCredentials and ServiceAccountCredentals
such that they provide JWTs as bearer tokens.

[CCLA](https://cla.developers.google.com/about/google-corporate) is in the works.  I thought I'd get the ball rolling with the review.

### CODE REVIEW

**Comment by maguro** [comment]
This PR is for https://github.com/google/google-auth-library-java/issues/157.

**Comment by maguro** [comment]
I wonder if `ServiceAccountCredentals` needs to customize the `forEsp()` method since there's `ServiceAccountJwtAccessCredentials`.

**Comment by chingor13** [comment]
Sorry for the delay in getting to this. Before we can review this PR, you'll need to sign one of CLA's mentioned above.

**Comment by chingor13** [comment]
Closing as the CLA hasn't been signed yet so we can't look into the PR yet. Feel free to reopen when the CLA is signed.

**Pull request closed without merging**
