### PR TITLE
Fix bom/README.md

### PR DESCRIPTION
**Pull request by kanterov**

### CODE REVIEW

**Comment by kanterov** [comment]
@googlebot I signed it!

**Comment by BenWhitehead** [comment]
@kanterov The email used for the commits in this PR (you're github no-reply email) isn't registered with your CLA signing. I'm going to ping a teammate offline to see what we can do here.

**Comment by kanterov** [comment]
@googlebot I signed it!

**Comment by kanterov** [comment]
@BenWhitehead I fixed the email. As far as I know, my employer has signed CLA, but it didn't seem to work as well. I'm fine with closing this PR if you can do this 1 char change yourself because it doesn't seem to worth our time :)

**Comment by BenWhitehead** [comment]
Thanks for the contribution @kanterov and being flexible. I've opened #372 with the fix and passing cla check.

**Pull request closed without merging**
